export const KEYS__ENG = {
  Backquote: ['`', `~`],
  Digit1: ['1', '!'],
  Digit2: ['2', '@'],
  Digit3: ['3', '#'],
  Digit4: ['4', '$'],
  Digit5: ['5', '%'],
  Digit6: ['6', '^'],
  Digit7: ['7', '&'],
  Digit8: ['8', '*'],
  Digit9: ['9', '('],
  Digit0: ['0', ')'],
  Minus: ['-', '_'],
  Equal: ['=', '+'],
  Backspace: ['Backspace'],
  // 
  Tab: ['Tab'],
  KeyQ: ['q', 'Q'],
  KeyW: ['w', 'W'],
  KeyE: ['e', 'E'],
  KeyR: ['r', 'R'],
  KeyT: ['t', 'T'],
  KeyY: ['y', 'Y'],
  KeyU: ['u', 'U'],
  KeyI: ['i', 'I'],
  KeyO: ['o', 'O'],
  KeyP: ['p', 'P'],
  BracketLeft: ['[', '{'],
  BracketRight: [']', '}'],
  Backslash: ['\\', '|'],
  // 
  CapsLock: ['CapsLock', 'CapsLock'],
  KeyA: ['a', 'A'],
  KeyS: ['s', 'S'],
  KeyD: ['d', 'D'],
  KeyF: ['f', 'F'],
  KeyG: ['g', 'G'],
  KeyH: ['h', 'H'],
  KeyJ: ['j', 'J'],
  KeyK: ['k', 'K'],
  KeyL: ['k', 'K'],
  Semicolon: [';', ':'],
  Quote: ['\'', '"'],
  Enter: ['Enter', 'Enter'],
  // 
  ShiftLeft: ['Shift', 'Shift'],
  KeyZ: ['z', 'Z'],
  KeyX: ['x', 'X'],
  KeyC: ['c', 'C'],
  KeyV: ['v', 'V'],
  KeyB: ['b', 'B'],
  KeyN: ['n', 'N'],
  KeyM: ['m', 'M'],
  Comma: [',', '<'],
  Period: ['.', '>'],
  Slash: ['/', '?'],
  ArrowUp: ['ArrowUp', 'ArrowUp'],
  ShiftRight: ['ShiftRight', 'ShiftRight'],
  // 
  ControlLeft: ['Control', 'Control'],
  MetaLeft: ['MetaLeft', 'MetaLeft'],
  AltLeft: ['Alt', 'Alt'],
  Space: [' ', ' '],
  AltRight: ['Alt', 'Alt'],
  ControlRight: ['Control', 'Control'],
  ArrowLeft: ['ArrowLeft', 'ArrowLeft'],
  ArrowDown: ['ArrowDown', 'ArrowDown'],
  ArrowRight: ['ArrowRight', 'ArrowRight'],
}

export const KEYS__RUS = {
  Backquote: ['ё', `Ё`],
  Digit1: ['1', '!'],
  Digit2: ['2', '"'],
  Digit3: ['3', '№'],
  Digit4: ['4', ';'],
  Digit5: ['5', '%'],
  Digit6: ['6', ':'],
  Digit7: ['7', '?'],
  Digit8: ['8', '*'],
  Digit9: ['9', '('],
  Digit0: ['0', ')'],
  Minus: ['-', '_'],
  Equal: ['=', '+'],
  Backspace: ['Backspace'],
  // 
  Tab: ['Tab'],
  KeyQ: ['й', 'Й'],
  KeyW: ['ц', 'Ц'],
  KeyE: ['у', 'У'],
  KeyR: ['к', 'К'],
  KeyT: ['е', 'Е'],
  KeyY: ['н', 'Н'],
  KeyU: ['г', 'Г'],
  KeyI: ['ш', 'Ш'],
  KeyO: ['щ', 'Щ'],
  KeyP: ['з', 'З'],
  BracketLeft: ['х', 'Х'],
  BracketRight: ['ъ', 'Ъ'],
  Backslash: ['\\', '/'],
  // 
  CapsLock: ['CapsLock', 'CapsLock'],
  KeyA: ['ф', 'Ф'],
  KeyS: ['ы', 'Ы'],
  KeyD: ['в', 'В'],
  KeyF: ['а', 'А'],
  KeyG: ['п', 'П'],
  KeyH: ['р', 'Р'],
  KeyJ: ['о', 'О'],
  KeyK: ['л', 'Л'],
  KeyL: ['д', 'Д'],
  Semicolon: ['ж', 'Ж'],
  Quote: ['э', 'Э'],
  Enter: ['Enter', 'Enter'],
  // 
  ShiftLeft: ['Shift', 'Shift'],
  KeyZ: ['я', 'Я'],
  KeyX: ['ч', 'Ч'],
  KeyC: ['с', 'С'],
  KeyV: ['м', 'М'],
  KeyB: ['и', 'И'],
  KeyN: ['т', 'Т'],
  KeyM: ['ь', 'Ь'],
  Comma: ['б', 'Б'],
  Period: ['ю', 'Ю'],
  Slash: ['.', ','],
  ArrowUp: ['ArrowUp', 'ArrowUp'],
  ShiftRight: ['ShiftRight', 'ShiftRight'],
  // 
  ControlLeft: ['Control', 'Control'],
  MetaLeft: ['MetaLeft', 'MetaLeft'],
  AltLeft: ['Alt', 'Alt'],
  Space: [' ', ' '],
  AltRight: ['Alt', 'Alt'],
  ControlRight: ['Control', 'Control'],
  ArrowLeft: ['ArrowLeft', 'ArrowLeft'],
  ArrowDown: ['ArrowDown', 'ArrowDown'],
  ArrowRight: ['ArrowRight', 'ArrowRight'],
}